task:
        vocab_id : 4 # task token in [0, 99)
        name: 'semantic_segmentation'
        segm_class_shift : 510
        tokens_registered: 4
        loss:

model:
        vocab_size : 2000 
        hidden_dim : 256
        size: 256 # this sets the image size for input, also the max_seq_len in decoder, make sure dataset also matches
        patch_size_sqrt: 8 #local model
        #backbone_weight : 'pretrained_weights/backbone/focalnet_tiny_srf_maskrcnn_1x.pth'
        in_channels : 3 #if use pretrained
        #model_weight: 'lightning_logs/2so0mmbf/checkpoints/epoch=50-step=167331.ckpt'
        model_weight: 'MegaByte-Pix2Seq/791nyvap/checkpoints/epoch=29-step=122550.ckpt'
        loss :
                        #loss : 'focal@2'

dataset:
    name: 'tissue_segmentation'
    batch_size: 8
    img_size: 256 # strictly for image size 256 and 1 channel, due to computation memory
    num_workers: 8
    train:
        input: '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_train/ct_norm'
        label: ['/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_train/csf_alt', 
               '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_train/gm_alt',
               '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_train/wm_alt']
        split: [0, 1]  #1 if not spliting, or 0.95
        size: 256
        augment: True #shuffle or SubsetRandomSampler    

    val:
        input: '/home/data_repo/braintissue/labels_norm_train/ct_norm'
        label: ['/home/data_repo/braintissue/labels_norm_train/csf_alt', 
               '/home/data_repo/braintissue/labels_norm_train/gm_alt',
               '/home/data_repo/braintissue/labels_norm_train/wm_alt']
        split: [0.95, 1]  #1 if not spliting, if train is 1 means there is no val set
        size: 256
        random: True #shuffle or SubsetRandomSampler   
        augment: False

    test:
        input: '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_test/ct_norm'
        label: ['/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_test/csf_alt', 
               '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_test/gm_alt',
               '/data/wang1448/FYP_WANG1448/previousFYPonOasis/oasis_fsl/labels_norm_test/wm_alt']
        split:   # all test
        size: 256
        random: True #shuffle or SubsetRandomSampler    
        augment: False

train:
        epoch : 50
